# Generated by Django 2.1.4 on 2018-12-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exclusoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Termo de procura',
                'verbose_name_plural': 'Termos de procura',
            },
        ),
        migrations.CreateModel(
            name='publicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PT', models.CharField(blank=True, max_length=200000, null=True)),
                ('AU', models.CharField(blank=True, max_length=200000, null=True)),
                ('BA', models.CharField(blank=True, max_length=200000, null=True)),
                ('BE', models.CharField(blank=True, max_length=200000, null=True)),
                ('GP', models.CharField(blank=True, max_length=200000, null=True)),
                ('AF', models.CharField(blank=True, max_length=200000, null=True)),
                ('BF', models.CharField(blank=True, max_length=200000, null=True)),
                ('CA', models.CharField(blank=True, max_length=200000, null=True)),
                ('TI', models.CharField(blank=True, max_length=200000, null=True)),
                ('SO', models.CharField(blank=True, max_length=200000, null=True)),
                ('SE', models.CharField(blank=True, max_length=200000, null=True)),
                ('BS', models.CharField(blank=True, max_length=200000, null=True)),
                ('LA', models.CharField(blank=True, max_length=200000, null=True)),
                ('DT', models.CharField(blank=True, max_length=200000, null=True)),
                ('CT', models.CharField(blank=True, max_length=200000, null=True)),
                ('CY', models.CharField(blank=True, max_length=200000, null=True)),
                ('CL', models.CharField(blank=True, max_length=200000, null=True)),
                ('SP', models.CharField(blank=True, max_length=200000, null=True)),
                ('HO', models.CharField(blank=True, max_length=200000, null=True)),
                ('DE', models.CharField(blank=True, max_length=200000, null=True)),
                ('ID_f', models.CharField(blank=True, max_length=200000, null=True)),
                ('AB', models.CharField(blank=True, max_length=200000, null=True)),
                ('C1', models.CharField(blank=True, max_length=200000, null=True)),
                ('RP', models.CharField(blank=True, max_length=200000, null=True)),
                ('EM', models.CharField(blank=True, max_length=200000, null=True)),
                ('RI', models.CharField(blank=True, max_length=200000, null=True)),
                ('OI', models.CharField(blank=True, max_length=200000, null=True)),
                ('FU', models.CharField(blank=True, max_length=200000, null=True)),
                ('FX', models.CharField(blank=True, max_length=200000, null=True)),
                ('CR', models.CharField(blank=True, max_length=200000, null=True)),
                ('NR', models.CharField(blank=True, max_length=200000, null=True)),
                ('TC', models.CharField(blank=True, max_length=200000, null=True)),
                ('Z9', models.CharField(blank=True, max_length=200000, null=True)),
                ('U1', models.CharField(blank=True, max_length=200000, null=True)),
                ('U2', models.CharField(blank=True, max_length=200000, null=True)),
                ('PU', models.CharField(blank=True, max_length=200000, null=True)),
                ('PI', models.CharField(blank=True, max_length=200000, null=True)),
                ('PA', models.CharField(blank=True, max_length=200000, null=True)),
                ('SN', models.CharField(blank=True, max_length=200000, null=True)),
                ('EI', models.CharField(blank=True, max_length=200000, null=True)),
                ('BN', models.CharField(blank=True, max_length=200000, null=True)),
                ('J9', models.CharField(blank=True, max_length=200000, null=True)),
                ('JI', models.CharField(blank=True, max_length=200000, null=True)),
                ('PD', models.CharField(blank=True, max_length=200000, null=True)),
                ('PY', models.CharField(blank=True, max_length=200000, null=True)),
                ('VL', models.CharField(blank=True, max_length=200000, null=True)),
                ('IS', models.CharField(blank=True, max_length=200000, null=True)),
                ('PN', models.CharField(blank=True, max_length=200000, null=True)),
                ('SU', models.CharField(blank=True, max_length=200000, null=True)),
                ('SI', models.CharField(blank=True, max_length=200000, null=True)),
                ('MA', models.CharField(blank=True, max_length=200000, null=True)),
                ('BP', models.CharField(blank=True, max_length=200000, null=True)),
                ('EP', models.CharField(blank=True, max_length=200000, null=True)),
                ('AR', models.CharField(blank=True, max_length=200000, null=True)),
                ('DI', models.CharField(blank=True, max_length=200000, null=True)),
                ('D2', models.CharField(blank=True, max_length=200000, null=True)),
                ('EA', models.CharField(blank=True, max_length=200000, null=True)),
                ('EY', models.CharField(blank=True, max_length=200000, null=True)),
                ('PG', models.CharField(blank=True, max_length=200000, null=True)),
                ('WC', models.CharField(blank=True, max_length=200000, null=True)),
                ('SC', models.CharField(blank=True, max_length=200000, null=True)),
                ('GA', models.CharField(blank=True, max_length=200000, null=True)),
                ('UT', models.CharField(blank=True, max_length=200000, null=True)),
                ('PM', models.CharField(blank=True, max_length=200000, null=True)),
                ('OA', models.CharField(blank=True, max_length=200000, null=True)),
                ('HC', models.CharField(blank=True, max_length=200000, null=True)),
                ('HP', models.CharField(blank=True, max_length=200000, null=True)),
                ('DA', models.CharField(blank=True, max_length=200000, null=True)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
    ]
