# Generated by Django 2.1.4 on 2018-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoPublicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacoes',
            name='Hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='UalgAfiliacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='centroInvestigacao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='pais',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='unidadeOriganica',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
