# Generated by Django 2.1.4 on 2018-12-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoPublicacoes', '0002_auto_20181225_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='UalgAfiliacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
