# Generated by Django 2.1.4 on 2018-12-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoPublicacoes', '0003_auto_20181225_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Termo de procura paises',
                'verbose_name_plural': 'Termos de procura paises',
            },
        ),
        migrations.CreateModel(
            name='termosHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Termo de procura hospital',
                'verbose_name_plural': 'Termos de procura hospital',
            },
        ),
        migrations.CreateModel(
            name='termosUalg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Termo de procura ualg',
                'verbose_name_plural': 'Termos de procura ualg',
            },
        ),
        migrations.CreateModel(
            name='termosUnidadeOrganica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Termo de procura UO',
                'verbose_name_plural': 'Termos de procura UO',
            },
        ),
        migrations.RenameModel(
            old_name='exclusoes',
            new_name='centroInvestigacao',
        ),
        migrations.AlterModelOptions(
            name='centroinvestigacao',
            options={'verbose_name': 'Termo de procura centro de investigacao', 'verbose_name_plural': 'Termos de procura centro de investigacao'},
        ),
    ]
