# Generated by Django 2.1.4 on 2018-12-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoPublicacoes', '0004_auto_20181225_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='Hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
